repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    -   id: check-yaml
-   repo: local
    hooks:
      - id: fmt
        name: fmt
        language: system
        files: '\.rs$'
        entry: cargo fmt -- --check # rustup run nightly rustfmt

      - id: clippy
        name: clippy
        language: system
        files: '\.rs$'
        entry: cargo clippy --all-targets --all -- -Dwarnings 
        pass_filenames: false